// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github/Slowhigh/go-study/go_labs/wire/event"
	"github/Slowhigh/go-study/go_labs/wire/greeter"
	"github/Slowhigh/go-study/go_labs/wire/message"
)

// Injectors from wire.go:

func InitializeEvent() (event.Event, error) {
	messageMessage := message.NewMessage()
	greeterGreeter := greeter.NewGreeter(messageMessage)
	eventEvent, err := event.NewEvent(greeterGreeter)
	if err != nil {
		return event.Event{}, err
	}
	return eventEvent, nil
}
